### ISSUE TITLE
The table on the front page isn't very clear

### ISSUE THREAD

**Issue by colindean** [fossfunders/fossfunders.com#25]
![image](https://github.com/fossfunders/fossfunders.com/assets/197224/fdda31f2-e9af-4da5-8404-d78a630c72e0)

I and some others with whom I've shared fossfunders.com are having trouble understanding what this table conveys. I _think_ it's trying to explain that FOSS Funders is prioritizing projects that want & need developer productivity tools, but the :x: don't really make sense to me.

**Comment by chadwhitacre** [comment]
Greetings @colindean and thanks for the feedback! 😁 How can we make this clearer? 🤔

**Comment by chadwhitacre** [comment]
> FOSS Funders is prioritizing projects that want & need developer productivity tools

Hrm, yeah, that's not it. "Want & Need" is a subheading under "Project's Relation to Money." It refers to money, not the categories on the left. In other words, this is a visualization of the emphasis defined in the previous paragraph—"especially developer productivity projects such as languages, libraries, frameworks, editors, and command-line tools"—together with a distinction between projects that don't want or need money and those that do.

Maybe this is clearer?

<img width="712" alt="Screenshot 2024-01-02 at 9 18 21 AM" src="https://github.com/fossfunders/fossfunders.com/assets/134455/5d1d74b9-7d66-4e2f-9203-39c9f7362203">

**Comment by colindean** [comment]
That's a big jump in the right direction because it clarifies what the columns mean as a variable of sorts. I think it's still not as clear as a paragraph might be:

> We fund end-user applications, operating systems, and developer productivity tools that have a sincere desire and demonstrated need for money in order to facilitate continued development and maintenance of the project. The highest level of funding is presently focused on developer productivity tools.

To me, this is much clearer, although I appreciate the charm of the emoji table.

**Comment by chadwhitacre** [comment]
> a paragraph might

We do already have a paragraph. 😛 The intention is to present the same info in two forms, so different people can digest it in different ways.

Let's move to https://github.com/fossfunders/fossfunders.com/pull/26, shall we?

**Comment by chadwhitacre** [comment]
Closing with #26. 👍
